fdo-rs/fido-device-onboard-rs

client-linuxapp/src/main.rs, data-formats/src/enhanced_types.rs, integration/testdata/owner-addresses.yml
- Fix small typo in data-formats/enhanced_types.rs
- Iterate over multiple owner addresses
Will help with #29
=> Support multiple owner addresses

README.md
Add more details around the components and initial details on building
locally on Fedora/RHEL/CentOS.
=> Update details on the README

client-linuxapp/src/main.rs, data-formats/Cargo.toml, data-formats/src/devicecredential/file.rs, data-formats/src/errors.rs, data-formats/src/ownershipvoucher.rs, data-formats/src/publickey.rs, data-formats/src/types.rs, http-wrapper/Cargo.toml, http-wrapper/src/client.rs, http-wrapper/src/lib.rs, owner-tool/src/main.rs, rendezvous-server/src/handlers_to1.rs, store/src/directory.rs
The abstract-crypto branch has been merged upstream, so let's resume
using that.
They did rename COSE -> Cose everywhere, so this updates that.
=> Move back to awslabs/aws-nitro-enclaves-cose

client-linuxapp/Cargo.toml, client-linuxapp/src/main.rs
Signed-off-by: Jose Noguera <jnoguera@redhat.com>
Closes #8
Related to #29
=> Implement TO1 and TO2 retries logic #8 #29

.mergify.yml
This should retain GPG signatures on commits
Signed-off-by: GitHub <noreply@github.com>
=> Use Merge instead of Rebase

http-wrapper/src/server.rs, owner-onboarding-service/src/main.rs, rendezvous-server/src/main.rs, store/src/directory.rs, store/src/in_memory.rs, store/src/lib.rs
This allows having a store that's marked read-only or write-only and
have this enforced by the type system.
=> Implement open modes for store

data-formats/src/types.rs, integration/test.sh, integration/testdata/rendezvous-info.yml, owner-tool/Cargo.toml, owner-tool/src/main.rs
Closes #36
Changes:
- Reformatted test script and added delay and inverted order in rendezvous test info file
- Working TO0 with multiple entries
=> Owner Tool: Run TO0 to every RV server listed in the RV info

client-linuxapp/Cargo.toml, client-linuxapp/src/main.rs, http-wrapper/Cargo.toml, http-wrapper/src/lib.rs, integration/test.sh, owner-onboarding-service/Cargo.toml, owner-onboarding-service/src/main.rs, owner-tool/src/main.rs, rendezvous-server/Cargo.toml, rendezvous-server/src/main.rs
This makes us use LOG_LEVEL instead of RUST_LOG for setting the logging
level.
This makes the fact that it's rust more hidden, because that is just an
implementation detail.
=> Use a timed and custom logger

.github/workflows/ci.yml
=> Only run CI on push when pushed to main

manufacturing-client/src/main.rs
The method to get the raw hmac key value from a PKey was added in a very
recent version of the OpenSSL crate.
This patch makes it so we pass along the raw byte buffer along, and just
construct a PKey when we need to compute an hmac.
=> fix(di-client): pass raw hmac key along

Cargo.toml, integration-tests/Cargo.toml, integration-tests/tests/common/mod.rs, integration-tests/tests/di_diun.rs, integration-tests/tests/to.rs, manufacturing-server/Cargo.toml, manufacturing-server/src/main.rs, owner-onboarding-server/Cargo.toml, owner-onboarding-server/src/main.rs, rendezvous-server/Cargo.toml, rendezvous-server/src/main.rs, util/Cargo.toml, util/src/lib.rs, util/src/servers.rs
=> feat: support configuration dropins

data-formats/src/types.rs
We make sure that nonce and guid values we receive from "externally"
(i.e. other parties to the protocol, ownership vouchers, etc), are of
the correct length (16 bytes long).
If we receive a value that is not exactly 16 bytes, we will fail to
deserialize.
Fixes: #98
=> fix: ensure Nonce and Guid are bstr .size 16

data-formats/src/constants.rs, data-formats/src/enhanced_types.rs
=> fix: support ips in rendezvous info

integration-tests/tests/common/mod.rs
Multiple tests in the same test suite should not collide with eachother,
since that would force executing them serially.
We already made sure that all tests run in their own temporary
directory, but we weren't making sure servers don't overlap in bound
ports.
Make sure that within one test suite (i.e. integration-test binary),
ports are chosen sequentially.
This means we can still overlap between different test suites (i.e.
di_diun vs to), but those aren't run in parallel by cargo test by
default anyway.
=> fix: ensure all tests use new server ports

data-formats/src/types.rs
We were wrapping the FDO payload of EAToken's inside a bstr, which is
not correct: the FDO payload is supposed to contain the actual CBOR
type.
=> fix: don't wrap EAT payload into a bstr

.github/workflows/ci.yml, .gitignore, docs/Gemfile, docs/_config.yml, docs/index.md, docs/specs/diun.md, docs/specs/index.md, docs/specs/ov_management_api.md, docs/specs/serviceinfo_api.md
This starts some in-tree documentation, to be built with GitHub Pages.
=> feat: create initial documentation framework

.mergify.yml
=> ci: fix mergify config file

data-formats/src/errors.rs, data-formats/src/types.rs, integration-tests/templates/owner-onboarding-server.yml.j2, integration-tests/tests/common/mod.rs, integration-tests/tests/to.rs, owner-onboarding-server/Cargo.toml, owner-onboarding-server/src/handlers.rs, owner-onboarding-server/src/main.rs, owner-tool/src/main.rs, store/src/directory.rs, util/src/servers.rs
=> feat: perform report to rendezvous periodically

integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/src/ownershipvoucher.rs, libfdo-data/src/test_common.rs, owner-onboarding-server/src/handlers.rs, owner-onboarding-server/src/main.rs, store/src/directory.rs
an immediate fix because after a full test I realized I wasn't getting the correct metadata in xattrs
also slightly adjust the query in directory store - far from being what we want but it's the only user _today_
=> fix: call async on futures

fido-device-onboard.spec
=> fix: add missing build dep and fix owner-tool location

fido-device-onboard.spec
=> fix(spec): use forgesource

client-linuxapp/Cargo.toml, client-linuxapp/src/serviceinfo.rs, integration-tests/Cargo.toml, integration-tests/templates/owner-onboarding-server.yml.j2, integration-tests/tests/common/mod.rs
Fix https://github.com/fedora-iot/fido-device-onboard-rs/issues/155
=> fix(serviceinfo): install ssh key with correct ownership

integration-tests/templates/manufacturing-server.yml.j2, integration-tests/templates/owner-onboarding-server.yml.j2, integration-tests/templates/rendezvous-server.yml.j2, integration-tests/tests/di_diun.rs, manufacturing-server/src/main.rs, owner-onboarding-server/src/main.rs, rendezvous-server/src/main.rs, store/src/directory.rs, util/Cargo.toml, util/src/servers.rs
Fix https://github.com/fedora-iot/fido-device-onboard-rs/issues/84
=> fix: check paths in configs are absolute

.github/commitlint.config.js, .github/workflows/ci.yml
=> chore: add commitlint configuration

http-wrapper/Cargo.toml, http-wrapper/src/server.rs, owner-onboarding-server/Cargo.toml, owner-onboarding-server/src/main.rs, rendezvous-server/Cargo.toml, rendezvous-server/src/handlers_to0.rs, store/Cargo.toml, store/src/directory.rs, store/src/lib.rs
This avoids a security issue in chrono, which is no longer maintained.
Fixes: #168
=> feat: move from chrono to time

.github/commitlint.config.js
=> ci: fix dependabot check

client-linuxapp/Cargo.toml, data-formats/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
=> feat: bump to v0.2.0

client-linuxapp/src/main.rs, manufacturing-client/src/main.rs, manufacturing-server/src/main.rs, owner-onboarding-server/src/main.rs, owner-tool/Cargo.toml, owner-tool/src/main.rs, rendezvous-server/src/main.rs, util/src/lib.rs
=> Add --version flag

fido-device-onboard.spec
=> fix(spec): Version has to come before forgemeta

examples/systemd/fdo-client-linuxapp.service
as documented in https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=
=> chore(systemd): env file is optional, mark it

admin-tool/src/main.rs
=> fix(admin-tool): randomize cert serial

integration-tests/tests/di_diun.rs, manufacturing-client/src/main.rs
=> feat: implement DIUN root cert verification

admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-dev-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
=> chore: bump version to 0.4.0

.github/workflows/ci.yml, docs/_config.yml
=> Use the official jekyll build action for CI

README.md
Add `tpm2-tss-devel` as a requirement.
=> chore: update build requirements on README.md

.devcontainer/Dockerfile, CONTRIBUTING.md
We also need TSS2 devel (for TPM support), and golang (for the Go
bindings).
Also sync up this list with the devcontainer DOCKERFILE.
=> chore: add more packages to CONTRIBUTING.md

admin-tool/Cargo.toml, admin-tool/src/aio/configure.rs, admin-tool/src/aio/device.rs, admin-tool/src/aio/execute.rs, admin-tool/src/aio/mod.rs, admin-tool/src/main.rs, client-linuxapp/src/main.rs, data-formats/src/types.rs, examples/config/manufacturing-server.yml, examples/config/owner-onboarding-server.yml, examples/config/rendezvous-server.yml, http-wrapper/src/client.rs, integration-tests/templates/manufacturing-server.yml.j2, integration-tests/templates/owner-onboarding-server.yml.j2, integration-tests/templates/rendezvous-server.yml.j2, integration-tests/templates/serviceinfo-api-server.yml.j2, integration-tests/tests/common/mod.rs, manufacturing-server/src/main.rs, owner-onboarding-server/src/main.rs, rendezvous-server/src/main.rs, serviceinfo-api-server/src/main.rs, store/src/directory.rs, store/src/lib.rs, util/Cargo.toml, util/src/servers/configuration/manufacturing_server.rs, util/src/servers/configuration/mod.rs, util/src/servers/configuration/owner_onboarding_server.rs, util/src/servers/configuration/rendezvous_server.rs, util/src/servers/configuration/serviceinfo_api_server.rs, util/src/servers/mod.rs
This implements an All-In-One server and device, to make it very easy to
set up an instance of FDO-rs for development and lab purposes.
Fixes: #241
=> feat: implement admin-tool All-In-One

docs/sims/encryption.md, docs/sims/index.md
=> doc: add documentation for diskencryption SIM

.github/workflows/ci.yml, CONTRIBUTING.md, client-linuxapp/Cargo.toml, client-linuxapp/src/main.rs, client-linuxapp/src/reencrypt/mod.rs, client-linuxapp/src/reencrypt/rebind.rs, client-linuxapp/src/serviceinfo.rs, data-formats/src/constants/mod.rs, data-formats/src/constants/serviceinfo_names.rs, data-formats/src/types.rs, integration-tests/Cargo.toml, integration-tests/tests/common/mod.rs, integration-tests/tests/e2e.rs, integration-tests/util_bins/clevis-decrypt-test, integration-tests/util_bins/clevis-encrypt-test, owner-onboarding-server/src/handlers.rs, serviceinfo-api-server/src/main.rs, util/src/servers/configuration/serviceinfo_api_server.rs, util/src/servers/mod.rs
This add re-encryption SIM implementation and test.
=> Add Reencryption implementation

admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, examples/config/manufacturing-server.yml, examples/config/serviceinfo-api-server.yml, examples/systemd/fdo-aio.service, examples/systemd/fdo-serviceinfo-api-server.service, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
=> chore(fido-device-onboard.spec): update to 0.4.5 latest

contrib/containers/README.md
Signed-off-by: Paul Whalen <pwhalen@redhat.com>
=> chore: add README.md for container image usage

HOWTO.md
Update the HOWTO.md
Clarify fields in owner-onboarding-server.yml, fix indentation in lists, update links and some other minor clarification updates.
=> docs: update links, clarify fields, fix indentation

CONTRIBUTING.md, TESTING.md
This PR contains
- update CONTRIBUTING.md file to provide detailed information on setting
up the build environment on Linux/mac machine.
- create a new file 'TESTING.md' to provide information on testing fdo
e2e scenario.
=> docs: update CONTRIBUTING.md build-env setup section & add TESTING.md

.github/workflows/ci.yml, client-linuxapp/src/serviceinfo.rs, integration-tests/Cargo.toml, integration-tests/tests/e2e.rs
Fixes #270 
This shall create initial user during the onboarding process.
=> fix(inital user creation) : create user during onboarding

admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
Prepare for the 0.4.6 release.
=> Bump for 0.4.6 release

admin-tool/Cargo.toml, admin-tool/src/aio/execute.rs
Fixes  #329
Signed-off-by: Irene Diez <idiez@redhat.com>
=> chore: replace chrono crate with time crate

.github/actions/build_containers/action.yml, contrib/containers/aio
=> chore: add AIO container

.github/workflows/cd.yml
=> chore: push aio image to quay

HOWTO.md
New device credential look up location was added in #204.
Signed-off-by: Irene Diez <idiez@redhat.com>
=> docs: update HOWTO with new Device Credential location

client-linuxapp/src/serviceinfo.rs, data-formats/src/types.rs, libfdo-data/build.rs, owner-onboarding-server/src/handlers.rs, owner-onboarding-server/src/main.rs, serviceinfo-api-server/src/main.rs
We are getting some errors on the CI of new PRs due to an update in clippy, so fix all the warnings in the codebase.
=> fix: general clippy warnings

contrib/containers/README.md
Signed-off-by: Paul Whalen <pwhalen@fedoraproject.org>
=> docs: fix formatting on containers/README.md

Cargo.lock, libfdo-data/Cargo.toml
=> chore: bump serial_test to 0.10.0

Cargo.lock, admin-tool/Cargo.toml, admin-tool/src/aio/configure.rs, client-linuxapp/Cargo.toml
Bumps nix to ~~0.24~~ 0.26, replace deprecated methods/structs.
=> chore: bump nix to 0.26

TESTING.md
This patch fixes the format of [TESTING.md](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/TESTING.md).
=> fix: format in TESTING.md

.packit.yaml
=> feat: integrate Packit with COPR

HOWTO.md
Updates the docs after the new feature in #451 .
Please note that the `plain-di` section has a couple of unexplained environment variables, and that is intended.
=> chore: update HOWTO.md

integration-tests/tests/e2e.rs
- line no 569-599 were accidentally repeated in e2e.rs , removed those.
=> test(e2e2): remove accidentally added block of lines

make-vendored-tarfile.sh
Some minor updates for the make-vendored-tarfile.sh script.
=> chore: minor updates to make vendored script

.github/actions/build_containers/action.yml, .github/workflows/cd.yml, contrib/containers/README.md, contrib/containers/client-linuxapp
This PR adds a fdo-client-linuxapp container.
- Updated CI/CD to include build of the container and push it to quay.io
- Updated README with commands to run the container
- FIxes #499
=> chore: add client-linuxapp container

Cargo.lock, admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, make-vendored-tarfile.sh, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
A few minor fixes in here, update the spec to create all the config directories.
=> Prepare 0.4.12

.github/workflows/integration.yaml, Makefile, test/check-ostree.yaml, test/fdo-container.sh, test/fdo/manufacturing-server.yml, test/files/centos-stream-9.json, test/setup.sh
1. change fdouser file location to workaround issue https://bugzilla.redhat.com/show_bug.cgi?id=2026795#c24
2. fix ssh key permission issue
3. run podman in root mode for network inter-connection
4. workflow job status fix
5. disable selinux on FDO server host and edge vm to workaround bug https://bugzilla.redhat.com/show_bug.cgi?id=2026795
6. fix Makefile `make rpm` failure
=> test: some fdo container test fixes

examples/systemd/fdo-client-linuxapp.service
=> fix: relabel devcreds before onboarding

README.md
=> docs: Update outdated FDO spec links

Cargo.lock, client-linuxapp/src/serviceinfo.rs, data-formats/Cargo.toml
=> fix: bump openssl-kdf to 0.4.2

HOWTO.md
add instructions to setup config environment variables when running in a dev container
=> docs: update HOWTO.md

HOWTO.md
Fix bullet points numbering from previous commit
=> fix(docs): Update HOWTO.md

.devcontainer/Dockerfile
=> fix: cargo test failing in dev container

.github/workflows/ci.yml
=> tests: add cargo test to dev container ci

Cargo.lock, client-linuxapp/Cargo.toml, fido-device-onboard.spec
Some spec and build fixes for downstream distro packaging.
=> Spec fixes

0001-Revert-chore-use-git-fork-for-aws-nitro-enclaves-cos.patch, Cargo.lock, admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, db/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-client/src/main.rs, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
Prepare for the 0.5.0 release.
=> chore: bump for 0.5.0 release

libfdo-data/src/lib.rs, owner-onboarding-server/src/handlers.rs, serviceinfo-api-server/src/main.rs
Fixes new clippy warnings that have pop up
Unlocks #650
=> fix: static-mut-refs warning

HOWTO.md, admin-tool/src/aio/configure.rs, examples/config/rendezvous-server.yml, owner-onboarding-server/src/handlers.rs, owner-onboarding-server/src/main.rs, rendezvous-server/src/handlers_to0.rs, rendezvous-server/src/main.rs, test/fdo/rendezvous-server.yml, test/fmf/tests/onboarding/run-onboarding.sh, util/src/servers/configuration/owner_onboarding_server.rs, util/src/servers/configuration/rendezvous_server.rs
- **feat(rendezvous-server)**: verify the device certificate chain
- **feat(owner-onboarding-server)**:  verify the device certificate chain
- **fix(owner-onboarding-server)**: spelling typos
Fixes: #628
=> feat: verify trusted manufacturers

Cargo.lock, admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, db/Cargo.toml, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml
This closes a security advisory.
=> chore: bump openssl to 0.10.66

.packit.yaml
very much like what we have in greenboot https://github.com/fedora-iot/greenboot/blob/main/.packit.yaml#L19C3-L38C29
=> chore(.packit.yaml): propose update when building

.github/dependabot.yml
=> dependabot: fix reviewers

Cargo.lock, admin-tool/Cargo.toml, client-linuxapp/Cargo.toml, data-formats/Cargo.toml, db/Cargo.toml, fido-device-onboard.spec, http-wrapper/Cargo.toml, integration-tests/Cargo.toml, libfdo-data/Cargo.toml, libfdo-data/fdo_data.h, manufacturing-client/Cargo.toml, manufacturing-server/Cargo.toml, owner-onboarding-server/Cargo.toml, owner-tool/Cargo.toml, rendezvous-server/Cargo.toml, serviceinfo-api-server/Cargo.toml, store/Cargo.toml, util/Cargo.toml
Prepare for the 0.5.2 release.
=> chore: bump for 0.5.2 release

Cargo.lock
I somehow missed a auto bump in the Cargo.lock.
=> chore: fix up cargo.lock

Cargo.lock, client-linuxapp/src/main.rs, client-linuxapp/src/serviceinfo.rs, data-formats/Cargo.toml, data-formats/src/cborparser.rs, data-formats/src/constants/serviceinfo_names.rs, data-formats/src/messages/v11/error.rs, data-formats/src/ownershipvoucher.rs, data-formats/src/types.rs, integration-tests/tests/service_info.rs, libfdo-data/src/ownershipvoucher.rs, libfdo-data/src/test_common.rs, patches/0001-Revert-chore-use-git-fork-for-aws-nitro-enclaves-cos.patch
Fix the aws-nitro-enclaves patches and serveral problems reported by clippy
=> Fix the aws-nitro-enclaves patches and serveral problems reported by clippy

.packit.yaml
as the title says
fixes https://github.com/fdo-rs/fido-device-onboard-rs/issues/742
=> packit: drop centos propose downstream and jobs

RELEASING.md
=> chore: describe how to release a new version

.github/spellcheck-ignore
=> ci: add spellcheck exceptions
