fdo-rs/fido-device-onboard-rs

- client-linuxapp/src/main.rs
- integration/test.sh
- integration/testdata/rendezvous-info.yml
Related to #8, will make easier implementing the retries.
Changes:
- Support for multiple rendezvous servers in the config file, and rename `get_client` to `get_client_list`.
- Split `get_to1d_from_rv` into `get_rv_info` and `get_to1d`.
- In the testing part:
- Add `-e` flag in `integration/test.sh`.
- Add one more rendezvous server (that won't be operating, just for the sake of dealing with multiple RV servers) in `integration/testdata/rendezvous-info.yml`.
> Client - Split RV & TO1. Support multiple rendezvous servers

- owner-onboarding-service/src/main.rs
- rendezvous-server/src/main.rs
- Moving configuration file to be optional will make it easier on deployments, also will make it easier by the user to catch the
configuration he's missing.
- Change prefix to fit bash/zsh export.
> Settings change

- data-formats/Cargo.toml
- data-formats/src/constants.rs
- data-formats/src/enhanced_types.rs
- data-formats/src/errors.rs
- data-formats/src/messages/di.rs
- data-formats/src/messages/error.rs
- data-formats/src/messages/mod.rs
- data-formats/src/messages/to0.rs
- data-formats/src/messages/to1.rs
- data-formats/src/messages/to2.rs
- data-formats/src/publickey.rs
- data-formats/src/types.rs
- http-wrapper/src/client.rs
- http-wrapper/src/lib.rs
- http-wrapper/src/server.rs
- owner-onboarding-service/src/main.rs
- rendezvous-server/src/main.rs
This enforces the ordering of messages within a session, by making both
the client and server check whether the next message is allowed at this
place of the protocol.
This would avoid possible issues where an attacker skips a part of the
process, skipping to the next part of the code.
This patch also includes metadata on the messages whether they're
required to be encrypted, which is checked by client and server.
> Make message ordering and encryption stronger

- .devcontainer/Dockerfile
- client-linuxapp/src/main.rs
- data-formats/src/enhanced_types.rs
- data-formats/src/errors.rs
- data-formats/src/ownershipvoucher.rs
- data-formats/src/publickey.rs
- integration/prepare.sh
- owner-onboarding-service/src/main.rs
- owner-tool/src/main.rs
- rendezvous-server/src/handlers_to0.rs
- rendezvous-server/src/handlers_to1.rs
When doing the initial implementation of PublicKey, we were expecting
X509 certificate DER data to be passed in, but we should instead be
sending and expecting DER encoded public keys.
During this, we also ensured that the DER data is correct at the moment
a PublicKey is constructed.
> Fix PublicKey data structure

- integration-tests/templates/manufacturing-service.yml.j2
- integration-tests/templates/owner-onboarding-service.yml.j2
- integration-tests/templates/rendezvous-service.yml.j2
- integration-tests/tests/to.rs
- store/src/directory.rs
Session IDs have a reasonable chance to have forward slashes in them,
since they're base64-encoded.
This patch makes the Directory driver replace the forward slashes with
"_slash_", to make sure that we can store those files.
Fixes: #53
> fix: make directory store driver replace slashes

- .github/dependabot.yml
- .github/workflows/ci.yml
This adds CI to enforce Conventional Commits[1] style commit messages.
If we make sure that further commit messages follow that, we can then
use a tool like git-cliff[2] to automatically generate changelogs.
[1]: https://www.conventionalcommits.org/en/v1.0.0/#summary
[2]: https://github.com/orhun/git-cliff
> ci: enforce conventional commits

- data-formats/src/constants.rs
- data-formats/src/messages/diun.rs
- data-formats/src/publickey.rs
- manufacturing-client/src/main.rs
- manufacturing-server/src/handlers/di.rs
- manufacturing-server/src/main.rs
- owner-onboarding-service/src/main.rs
- owner-tool/src/main.rs
- rendezvous-server/src/handlers_to0.rs
In PR #48, we changed the PublicKey structure to DER encoded public
keys, because that's how the specification reads.
Unfortunately, that is not the way it was intended: intended was an
actual DER-encoded X509 certificate (X509), or an x5chain (COSEX509).
This will be clarified in an upcoming erratum to the specification.
This patch brings it back to the correct structures.
> fix: bring PublicKey back to certificates

- .gitleaks.toml
This makes it so our ownership vouchers aren't alerted for by gitleaks
when we add the private keys.
> chore: ignore test vouchers with gitleaks

- client-linuxapp/Cargo.toml
- http-wrapper/Cargo.toml
- libfdo-data/Cargo.toml
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- store/Cargo.toml
The versions need to be specified for every crate in order to be
publishable to crates.io, until [1] gets implemented.
[1]: https://github.com/rust-lang/rfcs/blob/master/text/2906-cargo-workspace-deduplicate.md
> fix: add versions of internal dependencies

- .devcontainer/Dockerfile
Adding Golang to the dev container so Go wrapper tests can work.
> fix: adding golang to devcontainer

- data-formats/src/messages/mod.rs
These messages are not sent as an array with one element, but just the
one element.
> fix: (de)serialize simple messages correctly

- data-formats/src/types.rs
We make sure that the key exchanges (a_key_exchange and b_key_exchange)
are sent as bstr.
> fix: ensure KeyExchanges are bstr

- data-formats/src/types.rs
The random size from the spec is in bits, and we specify it in bytes.
Make sure that we generate and expect the correct number of random
bytes.
> fix: use correct lengths for random sizes

- integration-tests/templates/owner-onboarding-server.yml.j2
- owner-onboarding-server/src/handlers.rs
- owner-onboarding-server/src/main.rs
The CUPHOwnerPubKey is non-optional, so we make sure that we send the
owners public key.
> fix: add owner public key

- http-wrapper/src/server.rs
Make sure we log and return an error when an invalid message is sent,
instead of panic!'ing.
> fix: log and return error on sequence break

- client-linuxapp/src/main.rs
- data-formats/src/constants.rs
- owner-onboarding-server/src/handlers.rs
This was updated from an earlier draft, so update to use the correct key
for the nonce in the TO2 protocol.
> fix: use the correct nonce key for nonce7

- data-formats/src/types.rs
The ServiceInfo is a nested Vec, instead of just one Vec of KV pairs.
> fix: make ServiceInfo a Vec<Vec<KV>>

- data-formats/Cargo.toml
- data-formats/src/errors.rs
- data-formats/src/serializable.rs
The specification does not require CBOR canonical encoding, but some
other implementations do, due to the amount of nested data structures
that need to get hashes.
In order to make sure we generate contents they can correctly hash, this
changes us to use ciborium for serializing, since that generates
canonical CBOR (for the parts we care about).
This means we now have two CBOR libraries, and we might want to move to
ciborium fully further down the line, but at this moment using it for
just serializing is the easy-fix that gets us compatible with other
implementations.
> feat: use ciborium for serializing

- http-wrapper/src/client.rs
In the case of an error response, the server is not required to send a
message-type header.
We need to make sure we accept that, and then assume it's an Error
message.
> fix: allow missing messagetype in case of error

- http-wrapper/src/client.rs
If we use the automatic #[from], we also automatically get the source
registered, for tracebacks.
> fix: use error from for CoseError

- data-formats/Cargo.toml
- data-formats/src/types.rs
The KDF that was implemented as part of OpenSSL has hardcoded r=32 (the
length of the counter in the KDF is a 4-byte integer), while FDO
requires r=8 (a single-byte integer).
This means that we cannot use the one in OpenSSL, and have to implement
the KDF[1] ourselves.
[1]: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-108.pdf
> feat: implement custom KDF

- .github/workflows/labeler.yml
The labeler workflow needs permissions to update PRs in order to apply
labels.
> ci: fix permissions on labeler workflow

- client-linuxapp/src/main.rs
- data-formats/src/types.rs
If the to1d we received as part of the TO1 protocol is invalid, we need
to stop the TO2 that we were performing with that same to1d document.
Fixes: #81
> feat: cancel to2 if to1d was invalid

- .mergify.yml
For PRs that have a possible stability impact, we want to enforce extra
reviews.
Do this by requiring a second review for these PRs.
> ci: require extra review on stability impact

- http-wrapper/src/lib.rs
Make sure that by default we log at least at the INFO level, since that
is useful pretty important information.
Fixes: #130
> feat: default log level to info

- fido-device-onboard.spec
Hopefully the last PR around the spec file @nullr0ute :angel: 
This allows us to keep building with make rpm just fine and just change
the vendor tar gz downstream variable to version instead of commit.
> fix(spec): use forgesetup

- data-formats/Cargo.toml
- data-formats/src/errors.rs
- data-formats/src/types.rs
openssl-kdf has added the required functionality (custom r and ability
to skip L).
This allows us to use that implementation.
For now, we are using its custom implementation, until the required
patch is backported to OSSL1.1 and OSSL3.
> feat: switch back to openssl-kdf

- fido-device-onboard.spec
This allows us to have the same upstream and downstream spec file.
commit is needed for mainly dev and snapshots, version is what we really
use once we build downstream in Fedora/RHEL. `commit` is either defined in dev using forgemeta and Makefile or not set downstream (cause there we usually ship tagged versions)
> fix(spec): build with version if commit undefined

- client-linuxapp/src/main.rs
- data-formats/Cargo.toml
- data-formats/build.rs
- data-formats/src/lib.rs
- data-formats/src/types.rs
- http-wrapper/src/client.rs
- http-wrapper/src/server.rs
- integration-tests/tests/to.rs
- owner-onboarding-server/src/main.rs
This adds the ability to add a non-interoperable KDF implementation.
This should never be used in production environments, as it will be not
interoperable with other implementations, or this implementation with
the interoperable KDF.
When the non-interoperable KDF is enabled, the client and server will
send a header to indicate this, so it becomes possible for the other
side to dynamically fall back to the non-interoperable KDF when needed.
This is work for a future patch, but this ensures that such a patch will
have the required information.
> feat: add non-interoperable KDF

- client-linuxapp/Cargo.toml
- client-linuxapp/src/serviceinfo.rs
- data-formats/src/devicecredential/file.rs
- data-formats/src/types.rs
- integration-tests/templates/owner-onboarding-server.yml.j2
- integration-tests/tests/to.rs
- manufacturing-client/src/main.rs
- owner-onboarding-server/Cargo.toml
- owner-onboarding-server/src/serviceinfo/mod.rs
- owner-tool/src/main.rs
This implements a base `binaryfile` and `command` serviceinfo module set.
Both of them are currently quite hardwired on the server, but that can be changed later when the service info API gets implemented.
> Implement file and command serviceinfo modules

- store/src/directory.rs
There is now a lint that checks for this, since when running format!,
there's no need for a to_string().
> chore: don't call .to_string() in a format argument

- examples/systemd/fdo-client-linuxapp.service
mv may fail if creds aren't there - take that into account.
> chore(systemd): mv creds may fail

- dracut/52fdo/manufacturing-client-service
lsblk has hiccups on rhel9 for instance, use blkid instead
> chore(dracut): strenghten manufacturing client service

- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- fido-device-onboard.spec
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Bump the version number to 0.3.0 in preparation of a new release.
> chore: bump to version 0.3.0

- examples/config/manufacturing-server.yml
change store driver to Directory, we dropped InMemory
a while ago
> chore(examples/config): fix manufacturing server config

- examples/config/owner-onboarding-server.yml
lots of questions, make this clear :)
> chore(examples/config): paths must be absolute

- owner-tool/src/main.rs
Manually reporting to rendezvous via report-to-rendezvous has been
dropped and it is not implemented, so clean the remaining code.
> refactor(owner-tool): remove remnants of report-to-rendezvous subcommand

- examples/config/manufacturing-server.yml
- examples/config/owner-addresses.yml
- examples/config/owner-onboarding-server.yml
- examples/config/rendezvous-info.yml
- integration-tests/templates/manufacturing-server.yml.j2
- integration-tests/templates/owner-addresses.yml.j2
- integration-tests/templates/owner-onboarding-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/di_diun.rs
- integration-tests/tests/to.rs
- manufacturing-server/src/main.rs
- owner-onboarding-server/src/main.rs
Easier than having a separate file to link to - this patch still leaves
a rendezvous-info for tests and manual device init, we can revisit
later.
> embed rendezvous-info and owner-addresses in the config

- .github/workflows/ci.yml
- data-formats/Cargo.toml
- data-formats/src/devicecredential/file.rs
- data-formats/src/devicecredential/mod.rs
- data-formats/src/errors.rs
- integration-tests/templates/manufacturing-server.yml.j2
- integration-tests/templates/owner-onboarding-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/di_diun.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/to.rs
- manufacturing-client/Cargo.toml
- manufacturing-client/src/main.rs
- owner-tool/Cargo.toml
- owner-tool/src/main.rs
This implements a system where the keys for the device credential are
created by the TPM (never leaving the TPM), but the references to the
keys, and rendezvous info, etc, are stored on the filesystem.
This protects against having the actual private keys stolen when the
device credential file is extracted from a disk.
The current implementation only supports the ECDSA ciphers mentioned by
the FDO specification.
The current test suite does not set up a software TPM to execute the TPM
tests during CI, but it will execute the TPM tests if a TPM exists on
the system.
Fixes: #200
> feat: implement semi-TPM Device Credential

- Cargo.toml
- http-wrapper/Cargo.toml
- http-wrapper/src/client.rs
- integration-tests/templates/owner-onboarding-server.yml.j2
- integration-tests/templates/serviceinfo-api-dev-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/to.rs
- owner-onboarding-server/Cargo.toml
- owner-onboarding-server/src/handlers.rs
- owner-onboarding-server/src/main.rs
- serviceinfo-api-dev-server/Cargo.toml
- serviceinfo-api-dev-server/src/main.rs
- util/Cargo.toml
- util/src/servers.rs
This makes the Owner Onboarding Server use the ServiceInfo API for all
ServiceInfo data.
Fixes: #153
> feature: add serviceinfo API client

- client-linuxapp/src/main.rs
- data-formats/src/lib.rs
- data-formats/src/types.rs
- http-wrapper/src/client.rs
- http-wrapper/src/server.rs
- integration-tests/tests/to.rs
- manufacturing-client/src/main.rs
- manufacturing-server/src/handlers/diun.rs
- owner-onboarding-server/src/handlers.rs
- owner-onboarding-server/src/main.rs
- util/src/lib.rs
This adds functionality to the client and server to gracefully fall back
to the non-interoperable KDF if the other side requires it.
Fixes: #227
> feat: fall back to non-interoperable KDF

- .github/commitlint.config.js
This fixes a bug where commitlint fails to check if a commit is from
dependabot if it has no body at all.
It turns out that if a commit only has a header, the body becomes
`null`.
Let's make sure that that doesn't actually crash the check itself.
> ci: do not crash commitlint on missing body

- examples/config/owner-onboarding-server.yml
The sample config file does not work as it is
without the new required fields (service_info_api_url
and service_info_api_authentication), so incorporate
them.
(also, a clean version of #238 )
> chore: update sample owner config file

- docs/specs/serviceinfo_api.md
This adds the extra_commands part to the specification for ServiceInfo.
> feat: update ServiceInfo spec with extra_commands

- data-formats/Cargo.toml
There was two slightly different versions of openssl-kdf in the
Config.toml so unify them to make things consistent.
> chore: unify openssl-kdf versions in data-formats module

- admin-tool/src/aio/configure.rs
- integration-tests/templates/serviceinfo-api-server.yml.j2
- integration-tests/tests/e2e.rs
- serviceinfo-api-server/src/main.rs
- util/src/servers/configuration/serviceinfo_api_server.rs
This adds a simple configuration for the provided API server to return
clevis disk encryption.
> feat: add disk encryption to serviceinfo API server

- admin-tool/src/aio/mod.rs
In some packages, the binaries are stored in /usr/libexec/fdo, so make
it automatically detect the binaries from there as well.
> feat: support AIO with bindir in /usr/libexec/fdo

- examples/config/serviceinfo-api-server.yml
- fido-device-onboard.spec
a similar change was dropped when the sim server was split from the
onboarding server. Put this back.
> chore(examples): clarify paths again

- client-linuxapp/src/serviceinfo.rs
- data-formats/src/messages/mod.rs
- integration-tests/templates/serviceinfo-api-server.yml.j2
- integration-tests/tests/to.rs
- manufacturing-server/src/main.rs
- owner-onboarding-server/src/main.rs
- rendezvous-server/src/main.rs
Also add some unit testing. What this does is basically:
- make sure the path we get is always absolute, and do not join it with
the test variable before that check
- make sure paths are joined correctly in case there's a prefix from
environment variables (mainly for testing)
- refactor the struct/methods to be easy to add some unit test to
validate what we're writing
- also make sure we create the parents (mkdir -p) when writing a file (Fixes https://github.com/fedora-iot/fido-device-onboard-rs/issues/289)
> fix(client-linuxapp): refactor binary file in progress methods

- client-linuxapp/src/main.rs
iter returns a reference, ok to call it in the for just like this
> chore(client-linuxapp): drop a call to clone, use iter directly

- examples/config/rendezvous-server.yml
Update rendezvous-server.yml to include 'max_wait_seconds:' and updated storage path used in the AIO. This prevents a panic when trying to run the server without 'max_wait_seconds'.
This also removes the 'trusted_device_keys_path: /path/to/keys/device_ca_cert.pem', as it doesn't seem to be needed (not included in the config when running the fdo-aio). Please confirm before merging. 
Signed-off-by: Paul Whalen <pwhalen@redhat.com>
> Update example rendezvous-server.yml

- contrib/containers/README.md
- contrib/containers/manufacturing-server
- contrib/containers/owner-onboarding-server
- contrib/containers/rendezvous-server
- contrib/containers/serviceinfo-api-server
Add 'keys' directory to manufacturing, owner-onboarding and rendezvous dockerfiles.
Add 'device_specific_serviceinfo' to serviceinfo-api-server dockerfile.
Signed-off-by: Paul Whalen <pwhalen@redhat.com>
> chore: add expected directories to dockerfiles

- HOWTO.md
- examples/config/manufacturing-server.yml
- examples/config/rendezvous-info.yml
This contains general recipes on how to do things and documentation on the different command-line tools and config files that are in use.
Closes #300.
> docs: add a general HOWTO.md file

- data-formats/src/constants/mod.rs
Two MessageTypes are the same if they have the same code, we can derive both Eq and PartialEq.
This fixes a Clippy warning that we were getting on CI.
Closes #315
> fix: derive Eq on MessageType

- data-formats/src/ownershipvoucher.rs
Replace some println!-s in favour of log::info.
Closes #55
> refactor: replace println-s with log::info

- client-linuxapp/src/main.rs
- client-linuxapp/src/serviceinfo.rs
closes #202 
This PR contains fix for clientlinuxapp logging . When failing to install sshkey while performing fdo-onboarding , the errors were logged as 'TRACE' instead of 'ERROR' which makes it now easier for user to identify errors.
> fix (clientlinuxapp): Log ERROR when failing to install sshkey

- client-linuxapp/src/main.rs
This PR contains:
- fix for #201 
-  - fix error log for fdo-clientlinuxapp in case of failing to contact
rendezvous server.(e.g.wrong ip address)
- earlier the error msg was displayed as TRACE instead of ERROR
- no change in error message content.
- Error msg:
ERROR fdo_client_linuxapp  > Error performing TO1 with ServiceClient
ERROR fdo_client_linuxapp  > Error Couldn't get TO1 from any Rendezvous
server!getting usable To1d from rv_entry RendezvousInterpretedDirective
> fix(fdo-clientlinuxapp): fix error log for clientlinuxapp

- http-wrapper/Cargo.toml
There's a build issue with older versions of reqwest so bump to a release we know works.
> chore: bump reqwest to 0.11.9

- client-linuxapp/Cargo.toml
There's a build issue with newer versions of cryptsetup that needs a bugfix rust crate so bump from 0.5.0 to 0.5.1 to fix builds.
> chore: bump libcryptsetup to 0.5.1

- admin-tool/Cargo.toml
- manufacturing-server/Cargo.toml
- manufacturing-server/src/main.rs
- owner-onboarding-server/Cargo.toml
- owner-onboarding-server/src/main.rs
- rendezvous-server/Cargo.toml
- rendezvous-server/src/main.rs
- serviceinfo-api-server/Cargo.toml
- serviceinfo-api-server/src/main.rs
- store/Cargo.toml
- util/Cargo.toml
- util/src/servers/mod.rs
Bumps config crate to 0.13.2 and adds relevant changes due to deprecated methods.
Fixes #328 
Signed-off-by: Irene Diez <idiez@redhat.com>
> chore: bump config crate to 0.13.2

- docs/specs/ov_management_api.md
For uploading multiple ownership vouchers, the spec says, `vouchers should be appended to each other, adding a newline between the different entries`. But this newline isn't required; the code can split vouchers on encountering a new initial tag (-----BEGIN OWNERSHIP VOUCHER-----)
> fix: update spec for multiple vouchers

- util/src/device_credential_locations.rs
This will match fdo-linuxclient-app to the fdo-manufacturing-client
behavior.
Fixes-Issue: #203
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>
> default DEVICE_CREDENTIAL to /etc/device-credentials

- owner-tool/Cargo.toml
- owner-tool/src/main.rs
Migrate `owner-tool` to clap v3.1, with the derive format.
Closes #327.
> chore: port owner-tool to clap v3.1

- examples/config/rendezvous-info.yml
Wrong syntax in the current example file. Fxing it.
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
> rendezvous-info.yml: fix syntax

- client-linuxapp/Cargo.toml
No need to directly specify openssl dependency here.
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.com>
> build: client-linuxapp: remove redurant openssl dependency

- .mergify.yml
`rebase_fallback` is deprecated, remove the option from the queue settings.
Closes #365
> ci: remove deprecated option on mergify

- .github/workflows/ci.yml
Adds an aio check step to the CI to ensure that the command can be run in order to prevent further errors like #374
> ci: add aio check step to the build_and_test job

- .github/actions/build_containers/action.yml
This update removes the warnings showing in our CI due to Node.js 12 actions being deprecated.
> ci: update docker/metadata-action

- HOWTO.md
Fixes a typo in the `DEVICE_CREDENTIAL` env variable description.
> docs: fix typo in HOWTO.md

- Cargo.lock
- admin-tool/Cargo.toml
- admin-tool/src/aio/configure.rs
Checks the serialization and deserialization of the server configuration files.
This checks that converting Rust types to yaml files and back to Rust types does not break anything.
> ci: add tests for serde_yaml serialization + deserialization

- fido-device-onboard.spec
Removes rendezvous-info.yml from the install list for the aio command,
the contents of this file are already embedded into the manufacturing-server.yml file,
so aio does not need it.
This fixes the following error when trying to `make rpm` locally:
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files fido-device-onboard-rs/rpmbuild/BUILDROOT/fido-device-onboard-0.4.7-1.20230207gitdaa4a6c.el9.x86_64
error: Installed (but unpackaged) file(s) found:
/usr/share/doc/fdo/rendezvous-info.yml
```
> fix(spec): do not include unpackaged rendezvous-info.yml file

- examples/systemd/fdo-owner-onboarding-server.service
When using systemd units the `fdo-owner-onboarding-server.service` should also start `fdo-serviceinfo-api-server`.
> fix: owner-onboarding service should also start serviceinfoapi service

- Cargo.lock
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- fido-device-onboard.spec
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Prepare for the 0.4.8 release.
Update Cargo.lock file.
> chore: bump for 0.4.8 release

- examples/systemd/fdo-owner-onboarding-server.service
We'll go back to the way we used to start `fdo-owner-onboarding-server` and `fdo-serviceinfo-api-server`, with two separate systemd unit files that started each server and that's it.
The .spec file already ships each unit on `fdo-owner-onboarding-server` so on that RPM the user has everything that they need to start each server.
> fix: do not start two servers with the same unit

- http-wrapper/Cargo.toml
The reqwest crate is used in a number of places in FDO but it's only specified as minor releases in in the http-wrapper side of things. Let's align major versions as per the rest of the project.
> chore: don't require an explicit minor release of reqwest

- .github/workflows/ci.yml
- CONTRIBUTING.md
We use the latest Fedora version in a container to run our CI tests, due to the new release `/usr/share/cracklib/pw_dict.pwd.gz` is missing. This adds the `cracklib-dicts` package which provides the missing pieces.
> fix(ci): missing dependencies due to the new Fedora release

- HOWTO.md
- admin-tool/src/aio/configure.rs
- client-linuxapp/src/main.rs
- client-linuxapp/src/serviceinfo.rs
- data-formats/src/constants/serviceinfo_names.rs
- examples/config/serviceinfo-api-server.yml
- owner-onboarding-server/src/handlers.rs
- serviceinfo-api-server/src/main.rs
- util/src/servers/configuration/serviceinfo_api_server.rs
- util/src/servers/mod.rs
This adds a new serviceinfo api module `reboot` which allows
to specify if the system should be rebooted after onboarding
is completed.
This means that no client errors can be sent back since onboarding
is already considered to be a success. This reboot action is
always handled last, so any other onboarding action may fail
and will be handled according to the protocol. Only if onboarding
is successfully handled the reboot action will take place.
This reboot action is optional and can be configured in the
`serviceinfo-api-server.yml`
> Reboot option

- Cargo.lock
- admin-tool/Cargo.toml
Other modules in the project (rendezvous-server, store, http-wrapper and owner-onboarding-server) that also require `time` do not set an explicit minor version, so standardise this practice.
We did the same thing with `reqwest` on #427 .
This would close the automatic PR #429 from the bot too.
> chore(admin-tool): don't specify an explicit minor version for time

- .github/spellcheck-ignore
Both marshalling and marshaling are accepted words in Computer Science, see: https://en.wikipedia.org/wiki/Marshalling_(computer_science)
This unblocks #441
> chore: add 'marshalling' to spellcheck-ignore

- HOWTO.md
- admin-tool/src/aio/configure.rs
- serviceinfo-api-server/src/main.rs
- util/src/servers/configuration/serviceinfo_api_server.rs
This patch supports no authentication for service info by using `Option()`
for `service_info_auth_token`.
Current docs asks users to set `None` if no authentication is needed but
`serde_yaml` library does not handle the `None` as Rust's `None`. 
So this patch supports `service_info_auth_token` as `Option()` to allow
"no authentication is needed" when it is omitted.
Alternatively it is possible to support `"None"` or `""` (empty string)
as a special case to disable authorization. Any suggestion is welcome.
Fix https://github.com/fedora-iot/fido-device-onboard-rs/issues/403
> fix(serviceinfo): no authentication is needed when omitting `service_info_auth_token`

- Cargo.lock
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Prepare for the 0.4.9 release.
Update Cargo.lock file.
> chore: bump for 0.4.9 release

- .github/workflows/ci.yml
The organization `actions-rs` is unmaintained (see https://github.com/actions-rs/toolchain/issues/216). We are replacing the Github Actions that use it with `dtolnay/rust-toolchain`
Fixes #383
> ci: replace actions-rs/toolchain with dtolnay/rust-toolchain

- data-formats/src/cborparser.rs
This patch removes drops `get_hash_two_items` which is not called anywhere after the commit 865ca08.
> chore: remove unused function `get_hash_two_items`

- README.md
- docs/specs/serviceinfo_api.md
This patch adds missing [fdo-serviceinfo-api-server](https://github.com/fedora-iot/fido-device-onboard-rs/tree/main/serviceinfo-api-server) to the crates list in README.md.
> chore: add serviceinfo API server to crates list

- integration-tests/tests/e2e.rs
Current integration test does not work when `TPM2TOOLS_TCTI`, `TCTI` or `TEST_TCTI` is not set.
This patch sets `TEST_TCTI` when running tets with TPM.
Also, verify if /dev/tpm0 has the read permission.
Fix https://github.com/fedora-iot/fido-device-onboard-rs/issues/470
> ci: fix integration test with TPM

- Cargo.lock
- data-formats/Cargo.toml
- data-formats/src/ownershipvoucher.rs
- integration-tests/Cargo.toml
- integration-tests/tests/voucher_tests.rs
This PR picks up https://github.com/fedora-iot/fido-device-onboard-rs/pull/469 and fixes the build error by:
* Using `contents()` and `tag()` to access them.
* Using `pem::Pem::new()` to create a new Pem struct.
> chore: bump pem from 1.1.1 to 2.0.1

- Cargo.lock
- data-formats/Cargo.toml
- data-formats/src/cborparser.rs
As per `TODO` comment, current code does not support the value larther than 23 even though `read_len()` function supports it.
This patch adds the support.
Fix https://github.com/fedora-iot/fido-device-onboard-rs/issues/463
> feat(data-formats): Support encoding the large number by cborparser

- .github/workflows/ci.yml
- Cargo.lock
- HOWTO.md
- examples/config/device_specific_serviceinfo.yml
- integration-tests/templates/serviceinfo-api-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/to.rs
- serviceinfo-api-server/src/main.rs
- util/src/servers/configuration/serviceinfo_api_server.rs
- util/src/servers/mod.rs
This PR 
- provides a way to user for adding different initial user and sshkey by using `device_specific_store_driver` feature.
- user has to provide a .yml file with the same name GUID of the device under `device_specific_store_driver` path.
- If no file is present for a device then base config is applied (from serviceinfo_api_server.yml).
- updated HOWTO.md
> feat(serviceinfo_api_server): implement per device Serviceinfo initial user and sshkey

- HOWTO.md
- admin-tool/src/aio/configure.rs
- admin-tool/src/main.rs
Currently with the `generate-key-and-cert` option of the
`fdo-admin-tool` cli we can configure the 'Country' and
'Organization' name of the generated X509 certificate, and we
set by default a 365-day validity period.
This allows to set an specific number of days for the certificate's
validity period with the new `--validity-ends` option.
> feat(admin-tool): configure X509 certificate's expiration date 

- CONTRIBUTING.md
This specifies which Fedora releases are supported in the CONTRIBUTING guide so that the dependencies are valid.
Closes #481
> chore: specify supported Fedora releases in CONTRIBUTING

- Cargo.lock
- client-linuxapp/Cargo.toml
Update to the latest libcryptsetup-rs upstream release. Also update the Cargo.lock as part of this.
> chore: Update libcryptsetup-rs to 0.7

- Cargo.lock
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Prepare for the 0.4.10 release.
Update Cargo.lock file.
> chore: bump for 0.4.10 release

- Cargo.lock
- client-linuxapp/Cargo.toml
- client-linuxapp/src/reencrypt/mod.rs
- client-linuxapp/src/reencrypt/rebind.rs
- client-linuxapp/src/serviceinfo.rs
This potentially allows us to bump `libcryptsetup` to 0.8.0.
Closes #508
> chore: update libcryptsetup to 0.8.0 and fix API changes

- Cargo.lock
- client-linuxapp/Cargo.toml
- client-linuxapp/src/serviceinfo.rs
- integration-tests/Cargo.toml
- integration-tests/templates/serviceinfo-api-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/service_info.rs
- owner-onboarding-server/src/handlers.rs
- serviceinfo-api-server/src/main.rs
- util/src/servers/configuration/serviceinfo_api_server.rs
- util/src/servers/mod.rs
This pr attempts to implement the creation of a user and password when onboarding a device, using a username and password provided within the serviceinfo_api_server.yml config. 
closes https://github.com/fedora-iot/fido-device-onboard-rs/issues/321
This is a draft, current known issues include:
- Password encryption on on user creation
- Confirming sshkey creation still functional
- Confirming edge case functionality
> User creation with password

- client-linuxapp/src/reencrypt/mod.rs
- client-linuxapp/src/reencrypt/rebind.rs
- client-linuxapp/src/serviceinfo.rs
This explicitly marks LUKS2 as the load context to avoid getting `Operation incompatible with device marked for LUKS2 reencryption` errors.
Fixes rhbz#2216111
> fix: explicitly mark LUKS2 for context load

- client-linuxapp/src/serviceinfo.rs
- integration-tests/tests/common/mod.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/service_info.rs
- integration-tests/tests/to.rs
- owner-onboarding-server/src/handlers.rs
This change allows us to reproduce [RHBZ#2218231](https://bugzilla.redhat.com/show_bug.cgi?id=2218231) (and to catch more related bugs in the future)
and it also fixes that same BZ.
Our FSIM for creating users with an associated ssh key did
not take into account that ssh keys are strings that may
have spaces, e.g. 'ssh-ed25519 long-string user@example.com',
and used ' ' as the split character.
This sets ';' as the split character in the FSIM avoiding
installing unusable ssh keys.
> chore: update ssh-key format in tests to match real-world usage

- Cargo.lock
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- fido-device-onboard.spec
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
This updates the spec to the latest in Fedora and preps for 0.4.11
> Update rpm spec file and prepare for 0.4.11 release

- .github/workflows/integration.yaml
Package jq is required in "Get Current Job Log URL" step. It should be installed before use it.
Fix error in https://github.com/fedora-iot/fido-device-onboard-rs/actions/runs/5463148796/jobs/9943494222#step:2:9
> ci: install jq in "Get Current Job Log URL" step

- client-linuxapp/src/main.rs
- integration-tests/templates/serviceinfo-api-server.yml.j2
- integration-tests/tests/common/mod.rs
- integration-tests/tests/e2e.rs
- integration-tests/tests/service_info.rs
- integration-tests/tests/to.rs
This PR attempts to test if a user can be created with multiple ssh keys associated with it.
- Updates tests to check user creation with multiple ssh keys.
- Fixed clippy `using .borrow() on double reference` warnings.
closes #507
> [WIP] chore: Update e2e tests to check flow with multiple ssh keys per user

- HOWTO.md
- integration-tests/tests/di_diun.rs
- manufacturing-client/src/main.rs
This PR adds to mfg_string_type=MACAddress feat
- in case of mfg_string_type selected as  MACAddress and user has not provided which interface to use then get the default route and use that interface to get MACAddress.
- supports ipv4 network interface
- test is added
- updated HOWTO.md accordingly.
- fixes #468
> feat(manufacturing-client): use default ipv4 iface route if not provided

- Cargo.lock
- integration-tests/Cargo.toml
The use of sha-crypt was dropped with commit 8d1d1b2 but one of the Cargo.toml updates was missed so drop it there and update Cargo.lock to match.
Fixes: 8d1d1b2 ("chore: replace sha-crypt with openssl process calls")
> fix: drop unused sha-crypt dep

- Cargo.lock
- client-linuxapp/Cargo.toml
- client-linuxapp/src/serviceinfo.rs
- integration-tests/Cargo.toml
- integration-tests/tests/e2e.rs
- integration-tests/tests/service_info.rs
- util/src/lib.rs
- util/src/passwd_shadow.rs
This removes the dependencies on shadow and passwd from the project since we can accomplish the same functionality reading the /etc/shadow and /etc/passwd files.
> feat: replace shadow and passwd crates with our built-in functions

- make-vendored-tarfile.sh
We are setting a .tar.xz extension so we should build a .tar.xz instead of a bzip2. This sets such option in `make-vendored-tarfile.sh`
> fix: use J option (xz) instead of j (bzip2) for compression

- fido-device-onboard.spec
We removed the clients from the Requires list so the `fdo-aio.service` can't start. This fixes that.
Fixes rhbz#2230537
> fix(spec): add both clients as fdo-admin-cli's Requires

- HOWTO.md
- data-formats/src/messages/v11/diun.rs
- data-formats/src/messages/v11/to0.rs
- data-formats/src/messages/v11/to1.rs
- data-formats/src/messages/v11/to2.rs
- examples/config/serviceinfo-api-server.yml
Using the service-info-api server with selinux requires us to put anything we want to send to the device under /var/lib/fdo as that directory, and its files, will now get the correct selinux label. The previous approach opens up for security issues by leaving the process basically accessing the whole host.
> chore: fixup paths for selinux

- HOWTO.md
The configuration file names in `HOWTO.md` are inconsistent. Both the "_" and "-" syntax is used. This commit changes all occurences of the file names to the "-" syntax.
> docs(howto): fix config file names

- docs/sims/encryption.md
- docs/specs/serviceinfo_api.md
> fix: Spelling corrections

- admin-tool/src/aio/device.rs
Fix the `fdo-admin-tool aio device manufacture` command which fails
when running the `fdo-owner-tool dump-device-credential` command
after the manufacturing process has finished successfully.
Closes #563
> fix(admin-tool): call the 'fdo-owner-tool' with the correct arguments

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/tests/common/mod.rs
The users crate has been unmaintained for some time. This fix replaces its functionality with terminal commands resulting in the same output, and removes the users crate from the dependencies.
Fixes #566
> fix: integration-tests: remove users crate

- client-linuxapp/src/reencrypt/rebind.rs
- data-formats/src/publickey.rs
- data-formats/src/types.rs
fix clippy warnings after rustc v1.75.0 update
> chore: fix clippy warnings after rustc v1.75.0 update

- Cargo.lock
- http-wrapper/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
There's a pair of security issues in warp dependencies prior to 0.3.6 so bump this to at least that so we get the fixes forr
tungstenite and rustls dependencies.
> chore: bump warp requirement explicitly to 0.3.6

- .packit.yaml
- Cargo.lock
Fixes #506 
Builds are working for Fedora 40, Fedora 39 needs a package that is moving from testing to stable at the end of the day.
> chore: fix Fedora Packit builds

- manufacturing-server/src/handlers/di.rs
- owner-tool/src/main.rs
The specification states that “OVDevCertChainHash is the Hash of the concatenation of the contents of each byte string in OwnershipVoucher.OVDevCertChain, in the presented order."
The current behavior is to serialize the X5CHAIN to CBOR (i.e. `[ bstr[cert1] ... bstr[certN] ]` instead of `cert1 || ... || certN`).
See https://fidoalliance.org/specs/FDO/FIDO-Device-Onboard-PS-v1.1-20220419/FIDO-Device-Onboard-PS-v1.1-20220419.html#OwnershipVoucher
BREAKING CHANGE: The device certificate chain hash in ownership voucher is now calculated from the concatenation of certificate ASN.1 DER contents rather than the CBOR serialization of an array of byte strings.
> Fix hashing of Device Certificate Chain in Ownership Voucher

- Cargo.lock
- data-formats/Cargo.toml
- http-wrapper/Cargo.toml
- manufacturing-client/Cargo.toml
- owner-tool/Cargo.toml
There's a few minor fixes and no changes in API so let's bump to 7.4 for TPM2 support.
> chore: bump tss-esapi crate to 7.4

- Cargo.lock
- Cargo.toml
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- fido-device-onboard.spec
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Prepare for the 0.4.13 release. This has a fix
for how we deal with OVs as well as bumping
numerous crates with security issues.
> chore: bump for 0.4.13 release

- .devcontainer/devcontainer.json
People with a mac should use a podman machine that is _rootless_ and it works like a charm :)
> chore(devcontainer): setup for podman, add rust-analyzer

- 0001-Revert-chore-use-git-fork-for-aws-nitro-enclaves-cos.patch
Update the fedora patch to fix the aws-cose crate issue with the new version.
> chore: update patch for new release

- data-formats/src/constants/mod.rs
- data-formats/src/messages/v10/error.rs
- data-formats/src/messages/v11/error.rs
Use `serde_tuple` to serialize/deserialize the error messages
as a CBOR arrays instead of a CBOR maps as described in the
FIDO Device Onboard Specification.
Fixes: #620
> fix(data-formats): use serde_tuple serializer for error messages

- .github/workflows/ci.yml
- Cargo.lock
- client-linuxapp/src/serviceinfo.rs
- integration-tests/tests/common/mod.rs
- util/src/lib.rs
- util/src/system_info.rs
- **fix: add `system_info` module to `utils`**
- **fix: do not run tests that require root**
- **fix: use `system_info` mod functions to gather the current user name**
Fixes: #630
> fix: cargo test for non-root users

- util/src/system_info.rs
Remove traling whitespaces from `id -un` output.
> fix(get_current_user_name): remove trailing whitespaces.

- HOWTO.md
- admin-tool/src/aio/configure.rs
- owner-onboarding-server/src/main.rs
- store/src/db.rs
- store/src/directory.rs
- store/src/lib.rs
- util/src/servers/configuration/owner_onboarding_server.rs
This allows the users to specify an OV re-registration window in the Owner server. When an OV is about to be de-registered in the rendezvous server within the specified time window, the owner will trigger a re-registration.
Fixes #193 
Obsoletes #207
> Add an OV re-registration window option when using DB storage

- Cargo.lock
- db/src/lib.rs
- db/src/postgres.rs
- db/src/sqlite.rs
- manufacturing-server/Cargo.toml
- manufacturing-server/src/main.rs
- owner-onboarding-server/src/main.rs
- store/src/directory.rs
- store/src/lib.rs
- store/src/pg.rs
- store/src/sqlite.rs
Just serving an archive with all the OVs the manufacturer knows about.
It'd be handy to just give this away to whoever needs these credentials
and/or create a nice UI where you click a button to have them all.
The post-MVP, with a UI, would be to just have a UI that is able to list
all the device credentials, let you select which one you want, download
them in an archive, profit. Not there yet.
This is based on #671 - so let's merge that first
Signed-off-by: Antonio Murdaca <amurdaca@redhat.com>
> feat(manufacturing-server): implement an export OVs endpoint 

- dracut/52fdo/manufacturing-client.service
Run before coreos-installer-poweroff.service and
coreos-installer-noreboot.service systemd units.
Otherwise the coreos-installer-poweroff.service and
the manufacturing-client.service are run in parallel
and the manufacturing client can be stopped before
finishing the manufacturing process.
Resolves: RHEL-38482
> fix(systemd-units): run before powering off the system

- dracut/52fdo/manufacturing-client.service
Use 'isolate' instead of 'replace-irreversibly' for the manufacturing-client
service to prevent the `coreos-installer` service to be respawned when
the manufacturing-client fails.
> fix(dracut): use isolate on error in the manufacturing-client service

- Cargo.lock
- manufacturing-server/src/main.rs
- owner-tool/Cargo.toml
- owner-tool/src/main.rs
- test/fdo-postgres.sh
- test/fmf/tests/onboarding/run-onboarding.sh
This change allows the use of the new REST API to export either a single ov or multiple (tar-ed up).
Tested with the following:
```
$ ./target/debug/fdo-owner-tool export-manufacturer-vouchers --device-guid ba934a85-d55e-4930-0595-faeaa6090ddf http://localhost:8080
$ ./target/debug/fdo-owner-tool export-manufacturer-vouchers --device-guid ba934a85-d55e-4930-0595-faeaa6090ddf --path /home/amurdaca http://localhost:8080
$ ./target/debug/fdo-owner-tool export-manufacturer-vouchers http://localhost:8080 
```
> fix(owner-tool): use the new API to export ovs

- .packit.yaml
- test/fdo-postgres.sh
- test/fmf/plans/onboarding.fmf
Use the centos-stream-9 target as the epel-9 repos
don't seem to be up to date.
Remove the preparation steps enabling the copr repo
and installing the copr packages because it's not needed
and it's causing problems: Packit is supposed to enable the
copr repo and install all the packages contained in
that repo.
Use pipx instead of pip3 as suggested by the error
message to fix the postgres tests.
> fix: use centos-stream-9 target instead of epel-9

- .packit.yaml
- test/fmf/plans/onboarding.fmf
- test/fmf/tests/onboarding/run-onboarding.sh
- **chore: Move SELinux fixes to plan preparation steps**
- **fix(shellcheck): fix shellcheck lint issues**
- **chore: use a more meaningful name for generate_keys function**
- **test: simplify the code checking FDO services**
- **test: increase verbosity for FDO clients**
- **tests: add service infos to onboarding tests**
> enhance onboarding testing

- konflux/README.md
- konflux/fdo-container-test.yaml
- konflux/fdo-manufacturing-server-integration-tests.yaml
- konflux/fdo-owner-onboarding-server-integration-tests.yaml
- konflux/fdo-rendezvous-server-integration-tests.yaml
- konflux/fdo-serviceinfo-api-server-integration-tests.yaml
To enable integration test in konflux, this pr added test cases that will be triggered by konflux mr https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/2167
This pr only includes simple check for those containers, after this pr and related konflux mr get merged, I can start to trigger the workflow and debug errors. After the whole konflux integration test workflow is verified, more test cases can be added later.
I have a concern:
konflux will build single fido container and trigger test, for example, it build manufacturing server container and then trigger test for manufacturing server. Konflux currently cannot build all fido containers at the same time and then trigger the test.
This brings two questions: 
1. If I remember correctly some fido container depends on …
> ci: add konflux test cases

- libfdo-data/src/lib.rs
- make-vendored-tarfile.sh
I imagine we could get rid of all the tests/ directories in every create but for now, this addresses rpmlint in centos/rhel. See https://artifacts.osci.redhat.com/testing-farm/935ce55a-9d6d-4d11-be0a-7a0babd942b7/work-rpminspect20if1pvh/rpminspect/execute/data/guest/default-0/rpminspect-1/data/viewer.html#unicode We usually waived this kind of errors in the past but this is a good time and easy patch to fix it.
> fix(make-vendored-tarfile.sh): exclude idna tests with unicode points

- .packit.yaml
fixed packit configuration to allow to build the vendor archive in propose downstream too - as it's bad to add conditionals around sources anyway https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/#_do_not_conditionalize_sources
So, if we want just one shared specfile, this is the way :mandalorian:
> chore(packit): add pre-sync to fix propose-downstream action

- .packit.yaml
When somebody runs `packit propose-downstream` from the CLI, the MRs to update the spec are made by the user itself and not `packit`. When we merge these MRs, koji and bodhi won't run automatically unless we set allowed_builders/allowed_pr_authors, which this patch does.
> chore(.packit.yaml): allow committers to dist-git to trigger koji/bodhi

- Cargo.lock
Versions of rustls < 0.23.18 have CVEs so we need
to bump that and the associated rustls-pki-types dep.
We also bump warp a minor as it allows dropping the 
dep on the ancient rustls-pemfile rev and another dep.
> chore(deps): bump rustls to 0.23.18

- CONTRIBUTING.md
When trying to `cargo build` using Fedora 41, I needed to install the `sqlite` and `libpq` devel packages.
I also sync'ed the two lists of dependencies in the Fedora/toolbox examples for better consistency.
> chore: update CONTRIBUTING with additional deps

- .packit.yaml
Separate and reorder Fedora and CentOS build and test jobs. Also build and test CentOS stream 10.
Requires #725
> Packit changes

- .packit.yaml
Needed by the packit cli when we run propose-downstram
> fix: packit: bring back pkg_tool centpkg

- .packit.yaml
- Makefile
* Add two new `source-tarball` and `vendor-tarball` targets to generate the corresponding tarballs.
* Use the `vendor` target just to generate the filtered vendor directory and configure the cargo builds accordingly.
* Chain all the bash commands in the `vendor` target so all the bash variables contain the expected values.
* Adjust packit configuration to use the new `vendor-tarball`
> Makefile tarball targets

- Cargo.lock
- client-linuxapp/Cargo.toml
> chore: allow libcryptsetup-rs >= 0.11.2

- Cargo.lock
- admin-tool/Cargo.toml
- client-linuxapp/Cargo.toml
- data-formats/Cargo.toml
- db/Cargo.toml
- fido-device-onboard.spec
- http-wrapper/Cargo.toml
- integration-tests/Cargo.toml
- libfdo-data/Cargo.toml
- libfdo-data/fdo_data.h
- manufacturing-client/Cargo.toml
- manufacturing-server/Cargo.toml
- owner-onboarding-server/Cargo.toml
- owner-tool/Cargo.toml
- rendezvous-server/Cargo.toml
- serviceinfo-api-server/Cargo.toml
- store/Cargo.toml
- util/Cargo.toml
Bump versions for the 0.5.4 release, fix spec changelog.
I think this align with Fedora to fix the FTBFS with the various versions and bumps for CVEs
> chore: prepare 0.5.4 release

- contrib/containers/admin-cli
- contrib/containers/aio
- contrib/containers/manufacturing-server
- contrib/containers/owner-onboarding-server
- contrib/containers/rendezvous-server
- contrib/containers/serviceinfo-api-server
The aio (All In One) container is missing the DB client libraries and the deps for the FDO client to run, while at it drop the -devel packages for the services as they only need the actual libraries to run.
> chore: fix the container deps
